<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>DutWrapper.Tester</AssemblyName>
		<ProductVersion>1.8.0.5</ProductVersion>
		<FileVersion>$(ProductVersion)</FileVersion>
		<AssemblyVersion>$(ProductVersion)</AssemblyVersion>
		<RootNamespace>$(AssemblyName)</RootNamespace>
		<Title>$(AssemblyName)</Title>
		<Version>$(ProductVersion)</Version>
		<PackageProjectUrl>https://github.com/dutwrapper/dutwrapper-dotnet</PackageProjectUrl>
		<RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
		<!-- System.Text.Encoding.CodePages 7.0.0 doesn't support .NET Core 3.1, but this project works well for them. Maybe fail next time? -->
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.13.0" />
		<PackageReference Include="MSTest.TestAdapter" VersionOverride="3.8.3" />
		<PackageReference Include="MSTest.TestFramework" VersionOverride="3.8.3" />
		<PackageReference Include="coverlet.collector" VersionOverride="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DutWrapper\DutWrapper.csproj" />
	</ItemGroup>

</Project>
